<?php

namespace Pg\GsbFraisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TabletteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabletteRepository extends EntityRepository
{
}
